- example/android/app/build.gradle
- example/android/build.gradle
- example/lib/main.dart
- example/lib/tdesign/page/td_checkbox_page.dart
- example/lib/tdesign/page/td_radio_page.dart
- example/pubspec.lock
- lib/src/components/checkbox/td_check_box.dart
- lib/src/components/checkbox/td_check_box_group.dart
- lib/src/components/radio/td_radio.dart
- lib/src/components/radio/td_radio2.dart
- lib/src/theme/td_theme.dart
- lib/src/util/iterable_ext.dart
- lib/src/util/map_ext.dart
- lib/td_export.dart
- pubspec.lock
- [ **] 新特性提交
- [ **] 演示代码改进
- [** ] 其他
- fix(组件名称): 处理问题或特性描述 ...
> 1.增加TdCheckbox和TdRadio组件

- example/lib/main.dart
- example/lib/tdesign/page/td_bottom_navigation_bar_page.dart
- lib/src/components/bottom_nav_bar/td_bottom_nav_bar.dart
- lib/td_export.dart
> bottom nav bar

- example/lib/main.dart
- example/lib/tdesign/page/td_swiper_page.dart
- example/pubspec.lock
- example/pubspec.yaml
- lib/src/components/swiper/td_swiper.dart
- lib/td_export.dart
- pubspec.lock
- pubspec.yaml
> <feat>新增轮播图组件

- example/lib/main.dart
> fix compile

- example/lib/page/td_radio_page.dart
- lib/src/components/checkbox/td_check_box.dart
- lib/src/components/radio/td_radio.dart
https://github.com/TDesignOteam/tdesign-flutter/issues/35
> feat: Radio单选框组件变更需求

- example/lib/page/td_bottom_nav_bar_page.dart
- lib/src/components/bottom_nav_bar/td_bottom_nav_bar.dart
https://github.com/TDesignOteam/tdesign-flutter/issues/32
> <feat>TabBar底部标签需求

- example/assets/api/search_api.md
- example/lib/page/td_search_bar_page.dart
- lib/src/components/search/td_search_bar.dart
- [ ✔️] 新特性提交
https://github.com/TDesignOteam/tdesign-flutter/issues/28
Search搜索框组件样式变更
- [✔️ ] 文档已补充或无须补充
- [✔️ ] 代码演示已提供或无须提供
- [ ✔️] TypeScript 定义已补充或无须补充
- [ ✔️] Changelog 已提供或无须提供
> feat: 搜索框组件样式变更

- example/lib/page/td_checkbox_page.dart
- lib/src/components/checkbox/td_check_box.dart
- lib/src/components/checkbox/td_check_box_group.dart
> feat:Checkbox多选框组件变更

- example/lib/page/td_input_page.dart
- lib/src/components/input/td_input.dart
https://github.com/TDesignOteam/tdesign-flutter/issues/27
> feat: Input组件开发更新

- example/lib/page/td_badge_page.dart
- lib/src/components/badge/td_badge.dart
- 【feature】(徽标Badge): 徽标组件修改；按照示例稿进行布局
> 徽标组件修改；按照示例稿进行布局

- example/lib/page/td_toast_page.dart
- lib/src/components/toast/td_toast.dart
- fix(Toast轻提示组件): toast组件调整，按照实例页进行布局展示
> toast组件调整，按照实例页进行布局展示

- example/lib/page/td_divider_page.dart
- lib/src/components/divider/td_divider.dart
- fix(divider分割线): divider增加文字居左居右样式；示例代码调整
> divider增加文字居左居右样式；示例代码调整

- example/assets/code/text._buildCustomPaddingText.txt
- example/assets/code/text._buildGeneralProp.txt
- example/assets/code/text._buildNormalTDText.txt
- example/assets/code/text._buildRichText.txt
- example/assets/code/text._buildStyleCoverColor.txt
- example/assets/code/text._buildStyleCoverColorAndFont.txt
- example/assets/code/text._buildSystemText.txt
- example/assets/code/text._buildVerticalCenterText.txt
- example/assets/code/text._getSystemText.txt
- example/lib/page/td_text_page.dart
1.添加文本字体
2.修改文本演示代码
- fix(组件名称): 处理问题或特性描述 ...
> 修改Text演示代码

- example/lib/page/td_date_picker_page.dart
- example/lib/page/td_picker_page.dart
- lib/src/components/picker/td_date_picker.dart
- lib/src/components/picker/td_item_widget.dart
- lib/src/components/picker/td_multi_picker.dart
- lib/src/components/picker/td_picker.dart
- fix(tdPicker && tdDatetimePicker): 选择器和时间选择器样式修改，示例稿调整
> 选择器和时间选择器样式修改，示例稿调整

- example/lib/page/td_dialog_page.dart
- lib/src/components/dialog/td_alert_dialog.dart
- lib/src/components/dialog/td_confirm_dialog.dart
- lib/src/components/dialog/td_dialog_widget.dart
- lib/src/components/dialog/td_image_dialog.dart
- lib/src/components/dialog/td_input_dialog.dart
- fix(Dialog): 标题正文字号、颜色、轮廓圆角、间距等问题
> fix [Dialog] 标题正文字号、颜色、轮廓圆角、间距等问题 #85

- example/assets/code/tabs._buildItemWithOutlineCard.txt
- example/assets/code/tabs._buildItemWithSizeBig.txt
- example/assets/code/tabs._buildItemWithSizeSmall.txt
- example/assets/code/tabs._buildItemWithSplit1.txt
- example/assets/code/tabs._buildItemWithSplit2.txt
- example/assets/code/tabs._buildItemWithSplit3.txt
- example/assets/code/tabs._buildItemWithSplit4.txt
- example/assets/code/tabs._buildItemWithStatus.txt
- example/lib/page/td_refresh_page.dart
- [] 测试用例
- fix(组件名称): 处理问题或特性描述 ...
> 修改下拉刷新demo页示例

- example/lib/main.dart
- example/lib/page/td_slider_page.dart
- lib/src/components/silder/td_slider.dart
- lib/src/components/silder/td_slider_theme.dart
- lib/td_export.dart
https://github.com/TDesignOteam/tdesign-flutter/issues/97
https://github.com/TDesignOteam/tdesign-flutter/issues/122
新增组件：Slider滑动选择器
- 新增TDSlider TDRangeSlider
> 新增组件：Slider滑动选择器

- example/lib/page/td_input_page.dart
- lib/src/components/input/td_input.dart
> 输入框样式补全；示例代码修改

- example/lib/page/td_input_page.dart
- lib/src/components/input/td_input.dart
issue地址：https://github.com/TDesignOteam/tdesign-flutter/issues/77
- fix(input): input组件视觉走查修改
> input视觉走查修改

- example/lib/page/td_input_page.dart
- lib/src/components/input/td_input.dart
[](https://github.com/TDesignOteam/tdesign-flutter/issues/77)
> fix：样式走查修改

- example/assets/api/fab_api.md
- example/assets/code/fab._buildPureIconFab.txt
- example/assets/code/fab._buildShapeFab.txt
- example/assets/code/fab._buildSizeFab.txt
- example/assets/code/fab._buildTextFab.txt
- example/assets/code/fab._buildThemeFab.txt
- example/lib/main.dart
- example/lib/page/td_fab_page.dart
- lib/src/components/fab/td_fab.dart
- lib/td_export.dart
> 【Fab】新增fab悬浮按钮组件

- example/assets/api/tree_select_api.md
- example/assets/code/tree._buildDefaultTreeSelect.txt
- example/assets/code/tree._buildMultipleTreeSelect.txt
- example/assets/code/tree._buildThirdTreeSelect.txt
- example/lib/main.dart
- example/lib/page/td_tree_select_page.dart
- lib/src/components/sidebar/td_sidebar.dart
- lib/src/components/tree/td_tree_select.dart
- lib/td_export.dart
- feature(treeSelect): 新增树形选择器
> 【TreeSelect】新增树形选择器

- example/assets/api/back_top_api.md
- example/assets/code/backtop._buildCircleBackTop.txt
- example/assets/code/backtop._buildHalfCircleBackTop.txt
- example/lib/base/example_widget.dart
- example/lib/main.dart
- example/lib/page/td_backtop_page.dart
- lib/src/components/backtop/td_backtop.dart
- lib/td_export.dart
- feature(backtop): 新增backtop返回顶部组件
> feat: 新增backtop组件和api文档
